apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: search-toolbox
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/network-interfaces: '[{"network":"search-demo-vpc","subnetwork":"search-demo-vpc"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      serviceAccountName: search-backend-sa@iac-search-demo-test1.iam.gserviceaccount.com
      containers:
      - name: toolbox
        image: europe-west1-docker.pkg.dev/iac-search-demo-test1/search-app-repo/search-toolbox:20251208-152855
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          value: "Welcome01"
      
      # --- ALLOYDB AUTH PROXY SIDECAR ---
      - name: auth-proxy
        image: gcr.io/alloydb-connectors/alloydb-auth-proxy:latest
        args:
        - "projects/iac-search-demo-test1/locations/europe-west1/clusters/search-cluster/instances/search-primary"
        - "--address=127.0.0.1"
        - "--port=5432"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
