apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: search-agent
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/network-interfaces: '[{"network":"search-demo-vpc","subnetwork":"search-demo-vpc"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      serviceAccountName: search-backend-sa@iac-search-demo-test1.iam.gserviceaccount.com
      containers:
      - name: agent
        image: europe-west1-docker.pkg.dev/iac-search-demo-test1/search-app-repo/search-agent:20251208-152855
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "iac-search-demo-test1"
        - name: GOOGLE_CLOUD_REGION
          value: "europe-west1"
        - name: GOOGLE_CLOUD_LOCATION
          value: "europe-west1"
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: "true"
        - name: TOOLBOX_URL
          value: "https://search-toolbox-lzqdb3kvfa-ew.a.run.app"
